POST http://localhost:5000/app/signup
Content-Type: application/json


{
    "firstName":"samfds",
    "lastName":"mtal",
    "emailId":"abcdfdfdfdgdsdsdsd@@il.com",
    "userName":"heldsdso",
    "password":"yooyoyo"
}